/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.11.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as ai_chatgpt from "../ai/chatgpt.js";
import type * as ai_claude from "../ai/claude.js";
import type * as ai_common from "../ai/common.js";
import type * as engine from "../engine.js";
import type * as functions from "../functions.js";
import type * as games from "../games.js";
import type * as players from "../players.js";
import type * as problems from "../problems.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "ai/chatgpt": typeof ai_chatgpt;
  "ai/claude": typeof ai_claude;
  "ai/common": typeof ai_common;
  engine: typeof engine;
  functions: typeof functions;
  games: typeof games;
  players: typeof players;
  problems: typeof problems;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
